### ISSUE TITLE
ApachiCLI - missing regions

### ISSUE THREAD

**Issue by sohah** [sohah/VeritestingTransformations#32] opened 2019-03-27 22:06 UTC
I am writing all the issues we currently have, so we'd be able to get back to them in an organized way. 
This issue is happening in ApachiCLI, we are missing two regions which we used to veritest during our paper submission. This issue is happening on master, and also on the jitAnalysis branch.
The details of the regions and the exception raised are:
   benchmark: apachiCLI, running printtokens.3sym.mode5.jpf
    key: printTokens2.get_token(Ltoken_stream;)[C#43 
    exception: gov.nasa.jpf.symbc.veritesting.StaticRegionException: local output 54 to stack slot 4 does not have corresponding gamma statement

    benchmark: apachiCLI, running printtokens.3sym.mode5.jpf
    key: printTokens2.is_num_constant([C)Z#33
    exception: gov.nasa.jpf.symbc.veritesting.StaticRegionException: local output 12 to stack slot 1 does not have corresponding gamma statement 

I am assigning this to Vaibhav because he seemed to be interested in finding out what is going on.

**Comment by vaibhavbsharma** [comment] 2019-04-02 18:49
So far, I've found the following root causes of regions that have local outputs without a gamma statement at the end of the region summary.
1. The region summary has a return statement on one side of an if-statement and a local variable assignment on the other.
2. The local output is not used after the region (this one I am not so sure of, need to double-check. It happens in the last if-then statement in java.util.Integer.getChars(II[C)V.
3. The local variables that are the outputs go out of scope outside the region and therefore don't need gamma statements.

**Comment by vaibhavbsharma** [comment] 2019-04-02 20:13
After checking more than 25 instances where this assertion was violated, 23 of those originating from the Java library, I did not see any violations of this assertion that were correctness problems. The above 3 root causes summarize all of these assertion violations with root cause #2 (local output unused after region) being the rarest of the three and the other two root causes happening about equal number of times.

**Comment by vaibhavbsharma** [comment] 2019-04-02 20:41
closing this issue since I've removed the assertion whose violation was causing this bug.

**Closed by vaibhavbsharma** 2019-04-02 20:41 UTC
Labels: bug
