### ISSUE TITLE
Static Analysis for Early Return Skips Instructions in Return Blocks

### ISSUE THREAD

**Issue by sohah** [sohah/VeritestingTransformations#28] opened 2018-11-10 15:28 UTC
As per our meeting today, I am putting here the details of the problem I encountered for a concrete example.

The region I tried to verities is here:
`public static int earlyReturn2(int x, int y, int z) {
        if (x > 1) {
            return x * y;
        } else {
            return x + y;
        }
    }`

The statement we recover is 

`if ((! (<= w1 1 ) )) {
   w6 := (* w1 w2 ); 
   return 6
} else {
   skip; 
}
`
Where we are missing not only the instructions for the other return, but also the fact that there is a return on the other side as well.

**Comment by vaibhavbsharma** [comment] 2019-01-23 18:56
I can confirm we still have this bug. I ran into this issue when running the PrintTokens2_2 benchmark. In token_stream.EOFStream(), there is the below region:
```
        if (ch <= 0) {
            return true;
        }
        else {
            reader.unread(ch);
            return false;
        }
```
for which our static analysis produces the Ranger IR as:
```
if ((! (> w5 0 ) )) {
   return 7
} else {
   skip; 
}
```
As long as we don't have early-returns integrated into Java Ranger, this unsoundness should not be a problem because we will ask SPF to execute any regions with at least one return instruction. But, we need to fix this issue as part of integrating the RemoveEarlyReturns pass.

**Comment by vaibhavbsharma** [comment] 2019-01-23 19:47
This shouldn't exactly be considered a bug if the code on the `else` side does appear after these if-then-else statements.

**Comment by vaibhavbsharma** [comment] 2019-02-24 14:18
Closing this issue since this transformation seems to be working.

**Closed by vaibhavbsharma** 2019-02-24 14:18 UTC
