### ISSUE TITLE
ApacheCLI ClassCastException Raised while static analysis

### ISSUE THREAD

**Issue by sohah** [sohah/VeritestingTransformations#20] opened 2018-10-09 05:17 UTC
Running ApacheCLI from TSE'2017 [here](https://github.com/sohah/veritestingBenchmarks/tree/master/TSE-2017/ApacheCLI) with the jpf file [here ](https://github.com/sohah/veritestingBenchmarks/blob/master/TSE-2017/ApacheCLI/CLI.jpf) causes ClassCastException Raised during static analysis. The trace is below:

End of block: BB[SSA:2..5]2 - java.lang.Integer.stringSize(I)I
[SEVERE] JPF exception, terminating: exception during executeInstruction() notification
java.lang.ClassCastException: com.ibm.wala.shrikeBT.IShiftInstruction$Operator cannot be cast to com.ibm.wala.shrikeBT.IBinaryOpInstruction$Operator
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.Environment.SSAToStatIVisitor.visitBinaryOp(SSAToStatIVisitor.java:258)
	at com.ibm.wala.ssa.SSABinaryOpInstruction.visit(SSABinaryOpInstruction.java:48)
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.Environment.SSAToStatIVisitor.convert(SSAToStatIVisitor.java:472)
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.ssaToAst.CreateStaticRegions.translateInternalBlock(CreateStaticRegions.java:239)
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.ssaToAst.CreateStaticRegions.attemptSubregionRec(CreateStaticRegions.java:519)
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.ssaToAst.CreateStaticRegions.attemptSubregionRec(CreateStaticRegions.java:532)
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.ssaToAst.CreateStaticRegions.attemptMethodSubregion(CreateStaticRegions.java:565)
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.ssaToAst.CreateStaticRegions.createStructuredMethodRegion(CreateStaticRegions.java:632)
	at gov.nasa.jpf.symbc.veritesting.VeritestingMain.startAnalysis(VeritestingMain.java:292)
	at gov.nasa.jpf.symbc.veritesting.VeritestingMain.analyzeForVeritesting(VeritestingMain.java:154)
	at gov.nasa.jpf.symbc.VeritestingListener.discoverRegions(VeritestingListener.java:451)
	at gov.nasa.jpf.symbc.VeritestingListener.executeInstruction(VeritestingListener.java:171)
	at gov.nasa.jpf.vm.VM.notifyExecuteInstruction(VM.java:793)
	at gov.nasa.jpf.vm.ThreadInfo.executeInstruction(ThreadInfo.java:1904)
	at gov.nasa.jpf.vm.ThreadInfo.executeTransition(ThreadInfo.java:1859)
	at gov.nasa.jpf.vm.SystemState.executeNextTransition(SystemState.java:765)
	at gov.nasa.jpf.vm.VM.forward(VM.java:1722)
	at gov.nasa.jpf.search.Search.forward(Search.java:579)
	at gov.nasa.jpf.search.DFSearch.search(DFSearch.java:79)
	at gov.nasa.jpf.JPF.run(JPF.java:613)
	at gov.nasa.jpf.JPF.start(JPF.java:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at gov.nasa.jpf.tool.Run.call(Run.java:80)
	at gov.nasa.jpf.tool.RunJPF.main(RunJPF.java:116)
java.lang.AssertionError
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.Environment.SSAToStatIVisitor.createGamma(SSAToStatIVisitor.java:132)
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.Environment.SSAToStatIVisitor.translatePhi(SSAToStatIVisitor.java:216)
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.Environment.SSAToStatIVisitor.visitPhi(SSAToStatIVisitor.java:433)
	at com.ibm.wala.ssa.SSAPhiInstruction.visit(SSAPhiInstruction.java:90)
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.Environment.SSAToStatIVisitor.convert(SSAToStatIVisitor.java:472)
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.ssaToAst.CreateStaticRegions.translateInternalBlock(CreateStaticRegions.java:239)
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.ssaToAst.CreateStaticRegions.attemptSubregionRec(CreateStaticRegions.java:519)
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.ssaToAst.CreateStaticRegions.attemptSubregionRec(CreateStaticRegions.java:532)
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.ssaToAst.CreateStaticRegions.attemptSubregionRec(CreateStaticRegions.java:525)
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.ssaToAst.CreateStaticRegions.attemptSubregionRec(CreateStaticRegions.java:532)
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.ssaToAst.CreateStaticRegions.attemptSubregionRec(CreateStaticRegions.java:532)
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.ssaToAst.CreateStaticRegions.attemptSubregionRec(CreateStaticRegions.java:532)
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.ssaToAst.CreateStaticRegions.attemptMethodSubregion(CreateStaticRegions.java:565)
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.ssaToAst.CreateStaticRegions.createStructuredMethodRegion(CreateStaticRegions.java:632)
	at gov.nasa.jpf.symbc.veritesting.VeritestingMain.startAnalysis(VeritestingMain.java:292)
	at gov.nasa.jpf.symbc.veritesting.VeritestingMain.analyzeForVeritesting(VeritestingMain.java:154)
	at gov.nasa.jpf.symbc.VeritestingListener.discoverRegions(VeritestingListener.java:451)
	at gov.nasa.jpf.symbc.VeritestingListener.executeInstruction(VeritestingListener.java:171)
	at gov.nasa.jpf.vm.VM.notifyExecuteInstruction(VM.java:793)
	at gov.nasa.jpf.vm.ThreadInfo.executeInstruction(ThreadInfo.java:1904)
	at gov.nasa.jpf.vm.ThreadInfo.executeTransition(ThreadInfo.java:1859)
	at gov.nasa.jpf.vm.SystemState.executeNextTransition(SystemState.java:765)
	at gov.nasa.jpf.vm.VM.forward(VM.java:1722)
	at gov.nasa.jpf.search.Search.forward(Search.java:579)
	at gov.nasa.jpf.search.DFSearch.search(DFSearch.java:79)
	at gov.nasa.jpf.JPF.run(JPF.java:613)
	at gov.nasa.jpf.JPF.start(JPF.java:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at gov.nasa.jpf.tool.Run.call(Run.java:80)
	at gov.nasa.jpf.tool.RunJPF.main(RunJPF.java:116)
---------------------- JPF error stack trace ---------------------
gov.nasa.jpf.JPFListenerException: exception during executeInstruction() notification
	at gov.nasa.jpf.vm.VM.notifyExecuteInstruction(VM.java:800)
	at gov.nasa.jpf.vm.ThreadInfo.executeInstruction(ThreadInfo.java:1904)
	at gov.nasa.jpf.vm.ThreadInfo.executeTransition(ThreadInfo.java:1859)
	at gov.nasa.jpf.vm.SystemState.executeNextTransition(SystemState.java:765)
	at gov.nasa.jpf.vm.VM.forward(VM.java:1722)
	at gov.nasa.jpf.search.Search.forward(Search.java:579)
	at gov.nasa.jpf.search.DFSearch.search(DFSearch.java:79)
	at gov.nasa.jpf.JPF.run(JPF.java:613)
	at gov.nasa.jpf.JPF.start(JPF.java:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at gov.nasa.jpf.tool.Run.call(Run.java:80)
	at gov.nasa.jpf.tool.RunJPF.main(RunJPF.java:116)
Caused by: java.lang.AssertionError
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.Environment.SSAToStatIVisitor.createGamma(SSAToStatIVisitor.java:132)
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.Environment.SSAToStatIVisitor.translatePhi(SSAToStatIVisitor.java:216)
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.Environment.SSAToStatIVisitor.visitPhi(SSAToStatIVisitor.java:433)
	at com.ibm.wala.ssa.SSAPhiInstruction.visit(SSAPhiInstruction.java:90)
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.Environment.SSAToStatIVisitor.convert(SSAToStatIVisitor.java:472)
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.ssaToAst.CreateStaticRegions.translateInternalBlock(CreateStaticRegions.java:239)
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.ssaToAst.CreateStaticRegions.attemptSubregionRec(CreateStaticRegions.java:519)
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.ssaToAst.CreateStaticRegions.attemptSubregionRec(CreateStaticRegions.java:532)
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.ssaToAst.CreateStaticRegions.attemptSubregionRec(CreateStaticRegions.java:525)
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.ssaToAst.CreateStaticRegions.attemptSubregionRec(CreateStaticRegions.java:532)
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.ssaToAst.CreateStaticRegions.attemptSubregionRec(CreateStaticRegions.java:532)
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.ssaToAst.CreateStaticRegions.attemptSubregionRec(CreateStaticRegions.java:532)
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.ssaToAst.CreateStaticRegions.attemptMethodSubregion(CreateStaticRegions.java:565)
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.ssaToAst.CreateStaticRegions.createStructuredMethodRegion(CreateStaticRegions.java:632)
	at gov.nasa.jpf.symbc.veritesting.VeritestingMain.startAnalysis(VeritestingMain.java:292)
	at gov.nasa.jpf.symbc.veritesting.VeritestingMain.analyzeForVeritesting(VeritestingMain.java:154)
	at gov.nasa.jpf.symbc.VeritestingListener.discoverRegions(VeritestingListener.java:451)
	at gov.nasa.jpf.symbc.VeritestingListener.executeInstruction(VeritestingListener.java:171)
	at gov.nasa.jpf.vm.VM.notifyExecuteInstruction(VM.java:793)
	... 14 more

Process finished with exit code 0

**Comment by vaibhavbsharma** [comment] 2018-10-18 02:49
I've fixed this specific crash but I am running into the following different issue which I need to look into.

Caused by: java.lang.AssertionError
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.Environment.SSAToStatIVisitor.createGamma(SSAToStatIVisitor.java:133)
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.Environment.SSAToStatIVisitor.translatePhi(SSAToStatIVisitor.java:217)
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.Environment.SSAToStatIVisitor.visitPhi(SSAToStatIVisitor.java:440)
	at com.ibm.wala.ssa.SSAPhiInstruction.visit(SSAPhiInstruction.java:90)
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.Environment.SSAToStatIVisitor.convert(SSAToStatIVisitor.java:479)
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.ssaToAst.CreateStaticRegions.translateInternalBlock(CreateStaticRegions.java:239)
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.ssaToAst.CreateStaticRegions.attemptSubregionRec(CreateStaticRegions.java:519)
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.ssaToAst.CreateStaticRegions.attemptSubregionRec(CreateStaticRegions.java:532)
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.ssaToAst.CreateStaticRegions.attemptSubregionRec(CreateStaticRegions.java:525)
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.ssaToAst.CreateStaticRegions.attemptSubregionRec(CreateStaticRegions.java:532)
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.ssaToAst.CreateStaticRegions.attemptSubregionRec(CreateStaticRegions.java:532)
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.ssaToAst.CreateStaticRegions.attemptSubregionRec(CreateStaticRegions.java:532)
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.ssaToAst.CreateStaticRegions.attemptMethodSubregion(CreateStaticRegions.java:565)
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.ssaToAst.CreateStaticRegions.createStructuredMethodRegion(CreateStaticRegions.java:632)
	at gov.nasa.jpf.symbc.veritesting.VeritestingMain.startAnalysis(VeritestingMain.java:292)
	at gov.nasa.jpf.symbc.veritesting.VeritestingMain.analyzeForVeritesting(VeritestingMain.java:154)
	at gov.nasa.jpf.symbc.VeritestingListener.discoverRegions(VeritestingListener.java:455)
	at gov.nasa.jpf.symbc.VeritestingListener.executeInstruction(VeritestingListener.java:175)
	at gov.nasa.jpf.vm.VM.notifyExecuteInstruction(VM.java:793)
	... 14 more
Disconnected from the target VM, address: '127.0.0.1:56452', transport: 'socket'

Process finished with exit code 0

**Comment by vaibhavbsharma** [comment] 2018-10-18 21:16
I've fixed this specific crash in [this commit](https://github.com/sohah/VeritestingTransformations/commit/0672110c82299dacfca74f1b3da8e7abfe276b4d). When translating a phi, this commit makes us not summarize the region if the number of conditions isn't 1 when we expect it to be. In other words, for leaf-level assignments in SSAToStatIVisitor.createGamma(), the size of conditions should be 1.

Right after this fix, I ran into another crash with static analysis. This crash was happening because our static analysis tries to summarize all regions found in all classes in ${jpf-symbc}/build/examples as of now. This also contains [Pad.java](https://github.com/sohah/VeritestingTransformations/blob/master/src/examples/Pad.java) whose main function contains an infinite loop. This infinite loop is a problem for static analysis. I am made a change in [this commit](https://github.com/sohah/VeritestingTransformations/commit/fd2a7f079e5c84cba77cd3c5ced549e8567efdda) to use NatLoop for finding all loops in a Wala IR and detecting an infinite loop if a basic block is the start node of a loop but it doesn't have a conditional branch as its last instruction.

As of now, we're at least finishing executing through the Apache CLI benchmark. Now I will move on to checking if veritesting is any useful in this benchmark.

**Comment by vaibhavbsharma** [comment] 2018-10-23 14:29
Update: I've been trying to record the performance of veritesting with ApacheCLI. But, for some reason, we dont run into any symbolic conditions with ApacheCLI with 4 or 5 symbolic inputs to CLI.mainProcess. I need to further investigate why we dont see any symbolic conditions.

**Comment by vaibhavbsharma** [comment] 2019-02-24 14:17
Closing this issue because we were able to run into symbolic conditions with ApacheCLI and also instantiate regions for those conditions.

**Closed by vaibhavbsharma** 2019-02-24 14:17 UTC
